name: Deploy Firebase Functions

on:
  push:
    branches:
      - main
    paths:
      - 'functions/**'

jobs:
  deploy_functions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. Google Cloud에 인증 (우리가 만든 비밀 키 사용)
      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PROJECTPUBG_E5215 }}'

      # 2. Firebase CLI 도구 설치
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # 3. 라이브러리 설치 및 배포
      - name: Install dependencies and Deploy
        run: |
          cd functions
          npm ci
          firebase deploy --only functions --project projectpubg-e5215 --force